---
# vars file for transformers
- name: Include OS specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: Check if ImageMagick is installed
  command:
    cmd: "convert --version"
  register: magick_exists
  failed_when: false
  changed_when: magick_exists.rc != 0

- include_tasks: install-ImageMagick-depLibs.yml
  when: magick_exists.rc != 0


#- name: Ensure a list of packages installed
#  become: true
#  become_user: root
#  package:
#    name: "{{ item }}"
#    state: present
#  poll: 0
#  loop: "{{ utils_transform }}"

- name: Transfer ImageMagick libs
  copy:
    src: "{{ role_path }}/files/CentOS{{ ansible_distribution_major_version }}/ImageMagick"
    dest: "{{ download_location }}/"
  register: transfer_img_libs_dist
  until: transfer_img_libs_dist is succeeded
  when: magick_exists.rc != 0
  
  
- name: install imagemagick-distribution-libs
  yum:
    name: "{{ download_location }}/ImageMagick/imagemagick-distribution-7.0.10-11-libs-linux.rpm"
    disablerepo: "\\*"
    enablerepo: "offline-im"
    releasever: "{{ ansible_distribution_major_version }}"
    disable_gpg_check: yes
    state: present
  when: transfer_img_libs_dist is succeeded and magick_exists.rc != 0
  
- name: install imagemagick-distribution
  yum:
    name: "{{ download_location }}/ImageMagick/imagemagick-distribution-7.0.10-11-linux.rpm"
    disablerepo: "\\*"
    enablerepo: "offline-im"
    releasever: "{{ ansible_distribution_major_version }}"
    disable_gpg_check: yes
    state: present
  when: transfer_img_libs_dist is succeeded and magick_exists.rc != 0
  
...
