---
# tasks file for roles/java
- name: check for JDK on remote box
  stat:
    path: '{{ java_home }}'
  register: remote_java
  failed_when: false

- name: Download Java install file with check (md5)
  delegate_to: localhost
  become: false
  get_url:
    url: "{{ dependencies_url.jdk }}"
    #dest: "{{ download_location }}"
    dest: "{{ role_path }}/files"
    checksum: "md5:{{ jdk_md5_checksum }}"
    timeout: 570
  register: remote_jdk_tar
  when: not remote_java.stat.exists

- name: Unarchive jdk tar.gz
  unarchive:
    src: "../files/{{ jdk_tar_file }}"
    dest: "{{ download_location }}"
    remote_src: false
    mode: 'u=rwx,g=rx,o=rx'
  when: not remote_java.stat.exists

- name: Copy Java
  become: true
  become_user: root
  copy:
    src: "{{ download_location }}/{{ jdk_folder }}/"
    dest: "{{ java_home }}"
    remote_src: true
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
  when: not remote_java.stat.exists


- name: Check if setenv file exists
  stat:
    path: "{{ config_folder }}/setenv.sh"
  register: setenv_exists

- name: Add setenv bash file
  become: true
  become_user: "{{ username }}"
  template:
    src: setenv.sh
    dest: "{{ config_folder }}/setenv.sh"
    owner: "{{ username }}"
    group: "{{ group_name }}"
    mode: 'u=rwx,g=rx,o=rx'
  when: not setenv_exists.stat.exists
