---
# tasks file for roles/java
- name: check for JDK on remote box
  stat:
    path: '{{ java_home }}'
  register: remote_java
  failed_when: false

- name: Create Java Home directory
  file: 
    path: "{{ java_home}}/"
    state: directory

- name: Unarchive jdk tar.gz
  become: true
  become_user: root
  unarchive:
    # wget https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.7+10/OpenJDK11U-jdk_x64_linux_11.0.7_10.tar.gz
    src: ../files/OpenJDK11U-jdk_x64_linux_11.0.7_10.tar.gz 
    dest: "{{ java_home}}/"
    remote_src: no
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'    
  when: not remote_java.stat.exists

- name: Check if setenv file exists
  stat:
    path: "{{ config_folder }}/setenv.sh"
  register: setenv_exists

- name: Add setenv bash file
  become: true
  become_user: "{{ username }}"
  template:
    src: setenv.sh
    dest: "{{ config_folder }}/setenv.sh"
    owner: "{{ username }}"
    group: "{{ group_name }}"
    mode: 'u=rwx,g=rx,o=rx'
  when: not setenv_exists.stat.exists
