---
- name: Transformers Role
  hosts: transformers
  become: true
  become_method: sudo
  roles:
    - role: '../roles/transformers'
  tags:
    - transformers
  vars:
    #targetATSIP: ec2-52-207-219-201.compute-1.amazonaws.com
    targetATSIP: 52.91.199.69

    


