---
- name: Transformers Role
  hosts: transformers
  become: true
  become_method: sudo
  roles:
    - role: '../roles/transformers'
  tags:
    - transformers
  vars:
    targetATSIP: ec2-54-147-158-179.compute-1.amazonaws.com 

    


