  

- name: Shared File Store Role
  hosts: transformers
  become: true
  become_method: sudo
  roles:
    - { role: '../roles/sfs', when: acs.edition == "Enterprise" }
  tags:
    - sfs
  vars:
    targetATSIP: ec2-54-209-93-238.compute-1.amazonaws.com    
