---
# handlers file for activemq
- name: enable-activemq
  service:
    name: activemq
    enabled: true
    state: started
    daemon_reload: true
    
- name: restart-activemq
  service:
    name: activemq
    state: restarted
    daemon_reload: true

- name: stop-activemq
  service:
    name: activemq
    state: stopped
    daemon_reload: true

- name: start-activemq
  service:
    name: activemq
    state: started
    daemon_reload: true


